import { defaultSettings, createWorld } from '../src/sim/factory';
import { stepWorld } from '../src/sim/world';
import { generateOptions, rankOptions } from '../src/sim/decision';
const seed = process.argv[2] ?? 'meadow';
const name = process.argv[3] ?? 'Tomas';
const tick = Number(process.argv[4] ?? 45600);
const w = createWorld(defaultSettings(seed));
for (let i = 0; i < tick; i++) stepWorld(w);
const p = w.persons.find((q) => q.name === name)!;
console.log(`${p.name} t${w.tick} @${p.x.toFixed(1)},${p.y.toFixed(1)} thirst ${p.needs.thirst.toFixed(0)} hunger ${p.needs.hunger.toFixed(0)} home hh ${p.hhId}`);
const waters = (p.bykind.water ?? []).map((id) => p.beliefs[id]).map((b) => ({ x: b.x, y: b.y, d: Math.hypot(b.x - p.x, b.y - p.y), seen: w.tick - b.seen, src: b.src }));
waters.sort((a, b) => a.d - b.d);
console.log('known water cells', waters.length);
for (const q of waters.slice(0, 40)) console.log(`   (${q.x.toFixed(1)},${q.y.toFixed(1)}) d=${q.d.toFixed(1)} age=${q.seen} ${q.src}`);
const dangers = (p.bykind.danger ?? []).map((id) => p.beliefs[id]);
console.log('dangers', dangers.map((b) => `(${b.x.toFixed(0)},${b.y.toFixed(0)}) age ${w.tick - b.seen}`).join('; '));
const ctx = generateOptions(w, p, true);
const ranked = rankOptions(ctx);
for (const o of ranked.slice(0, 6)) console.log('   opt', o.kind, o.label, o.util.toFixed(1), JSON.stringify(o.parts), 'eta', o.eta.toFixed(0));
console.log('wolves', w.animals.map((a) => `${a.state}@${a.x.toFixed(0)},${a.y.toFixed(0)}`).join(' '));
